export enum NotificationType {
    NEW_LIKE = "NEW_LIKE",
    NEW_MATCH = "NEW_MATCH",
    NEW_MESSAGE = "NEW_MESSAGE",
    NEW_MATCH_IN_PROGRESS = "NEW_MATCH_IN_PROGRESS",
    ROOMMATE_LEFT_FLAT = "ROOMMATE_LEFT_FLAT",
    ROOMMATE_JOINED_FLAT = "ROOMMATE_JOINED_FLAT"
}
